package eff

import (
  "crypto/rand"
  "strings"
  "strconv"
  "math/big"
  "os"
  "bufio"
  "fmt"
  "regexp"
  "errors"
)

// DefaultSuffixChars is the alphanumeric character set for random suffixes,
// excluding visually ambiguous characters (0, O, 1, I, l).
const DefaultSuffixChars = "ABCDEFGHJKLMNPQRSTUVWXYZabcdefghjkmnpqrstuvwxyz23456789"

var reIndexedFileLine = regexp.MustCompile("^([1-6]{5})\\s+(.*)")

// GetWords will return a list of Diceware words
func GetWords(numberOfWords int) ([]string, error) {

  words := make([]string,numberOfWords)

  for i := 0; i < numberOfWords; i++ {
    words[i] = wordList[rollIndex()]
    if words[i] == "" {
      return words,errors.New("Word lookup returned empty result")
    }
  }

  return words,nil

}

// rollIndex returns a Diceware compliant index value.
func rollIndex() string{
  var index strings.Builder

  minInt := int64(1)
  maxInt := int64(6)

  for i := 1; i <= 5; i++ {
    randInt,rc := rand.Int(rand.Reader, big.NewInt(maxInt - minInt + 1))
    if rc != nil {
      panic(fmt.Sprintf("crypto/rand failure: %v", rc))
    }
    indexDigit := randInt.Int64() + minInt
    index.WriteString(strconv.FormatInt(indexDigit,10))
  }

  return index.String()

}

// GetRandomChars returns a string of n cryptographically random characters
// drawn uniformly from the provided charset.
func GetRandomChars(length int, charset string) (string, error) {
  if length < 0 {
    return "", errors.New("length must be non-negative")
  }
  if len(charset) == 0 {
    return "", errors.New("charset must not be empty")
  }

  result := make([]byte, length)
  charsetLen := big.NewInt(int64(len(charset)))
  for i := range result {
    n, err := rand.Int(rand.Reader, charsetLen)
    if err != nil {
      return "", fmt.Errorf("crypto/rand failure: %w", err)
    }
    result[i] = charset[n.Int64()]
  }
  return string(result), nil
}

// LoadWordFile loads a word list file to use in place of the default EFF word list.
// Expected word file formats are either:
//    - Two-column space delimited-list of diceware index and word
//    - One column list of words (diceware index will be auto-generated by the load function).
func LoadWordFile(filePath string) error{

  fileType := ""
  
  fileHandle, err := os.Open(filePath)

  if err != nil {
    return err
  }

  defer fileHandle.Close()

  fileReader := bufio.NewScanner(fileHandle)
  
  clear(wordList)

  currentIndex := NewDicewareNumber()

  for fileReader.Scan(){

    fileLine := fileReader.Text()    

    lineFields := reIndexedFileLine.FindStringSubmatch(fileLine)

    if lineFields != nil  {
      if fileType == "" {
        fileType = "indexed"
      } else if fileType != "indexed" {
        return errors.New("Mixed format file detected (indexed and single column list)")
      }

      wordList[lineFields[1]] = lineFields[2]
    } else {
      if fileType == "" {
        fileType = "wordOnly"
      } else if fileType != "wordOnly" {
        return errors.New("Mixed format file detected (indexed and single column list)")
      }

      wordList[currentIndex.StringValue()] = fileLine

      // Check for overflow.
      if len(wordList) > 7776{
        return errors.New(fmt.Sprint("Excessive word count: ", len(wordList), " instead of 7776 expected."))
      }

      currentIndex.Inc()
    }
  }

  if len(wordList) < 7776{
    return errors.New(fmt.Sprint("Insufficient words: ", len(wordList), " out of 7776 required."))
  }
  return nil
}
